### ISSUE TITLE
escalc change in behavior since 1.9-8 

### ISSUE THREAD

**Issue by dredan** [wviechtb/metafor#11]
Hi - I have some code I have been running a while on 1.9-8. I recently updated to 2.0-0 and having problem with escalc. It does not behave in the same way it used to. In short, the yi / vi is not being calculated at all. I can show examples from 1.9-8 and 2.0-0 below.

dataset:
```
              study n1i sd1i n2i sd2i   am  m1i m2i           vi      yi
1  Cahill KN (2017)  32   NA  30   NA   MD   NA  NA 2.603178e-05 0.04600
2 Bousquet J (2011) 272   NA 128   NA   MD   NA  NA 2.603178e-03 0.11000
3   Karpel J (2010) 542   NA 529   NA   MD   NA  NA 7.229779e-04 0.02876
4   Garcia G (2013)  20 0.38  21  0.2 <NA> 0.25   0           NA      NA
```

escalc call - same one used in 1.9-8 and 2.0-0 
```
es <- escalc("MD", m1i=m1i, n1i=n1i, sd1i=sd1i,
                   m2i=m2i, n2i=n2i, sd2i=sd2i,
                   yi=yi,vi=vi,
                   slab=study,data=p2$data,replace=FALSE)
```
result in 1.9-8 (it generated the yi/vi for the last study as expected)
```

              study n1i sd1i n2i sd2i   am  m1i m2i     vi     yi
1  Cahill KN (2017)  32   NA  30   NA   MD   NA  NA 0.0000 0.0460
2 Bousquet J (2011) 272   NA 128   NA   MD   NA  NA 0.0026 0.1100
3   Karpel J (2010) 542   NA 529   NA   MD   NA  NA 0.0007 0.0288
4   Garcia G (2013)  20 0.38  21  0.2 <NA> 0.25   0 0.0091 0.2500
```

result in 2.0-0 (in the last study the yi/vi was not generated)
```
              study n1i sd1i n2i sd2i   am  m1i m2i           vi      yi
1  Cahill KN (2017)  32   NA  30   NA   MD   NA  NA 2.603178e-05 0.04600
2 Bousquet J (2011) 272   NA 128   NA   MD   NA  NA 2.603178e-03 0.11000
3   Karpel J (2010) 542   NA 529   NA   MD   NA  NA 7.229779e-04 0.02876
4   Garcia G (2013)  20 0.38  21  0.2 <NA> 0.25   0           NA      NA
```

maybe the change in behavior is documented somewhere but I could not find it.

thank you!

**Comment by wviechtb** [comment]
I think this change in behavior is related to a change in 1.9-9 (in NEWS: `one can now pass an 'escalc' object directly to rma.uni() [...]`). But the code you are using is using unintended syntax anyway -- why are you using `yi=yi` and `vi=vi` in your `escalc()` call? You should just use:

```
es <- escalc("MD", m1i=m1i, n1i=n1i, sd1i=sd1i,
                   m2i=m2i, n2i=n2i, sd2i=sd2i,
                   slab=study,data=p2$data,replace=FALSE)
```

And then in works as it should.

**Comment by dredan** [comment]
Hi - I pass in yi/vi because some of the data I get in the dataset already has a yi/vi and is mixed with studies that don't.. escalc 1.9-8 and prior did a great job of just filling in the missing data for me and leaving the original data alone via `replace=FALSE` parameter.

**Comment by dredan** [comment]
ok - i tested your suggestion and it works. thank you.
