### ISSUE TITLE
how are weights assigned with rma.mv? 

### ISSUE THREAD

**Issue by nadinevogt** [wviechtb/metafor#13]
Hi there,

I am new to meta-analysis and relatively new to R, and am hoping for some advice regarding a meta-analysis! I am using a rma.mv model to account for clustering by trials that use the same comparator group for multiple treatment groups. The data we are working with is pretty sparse... several studies have 0 events for both treatment and comparator groups. Is this an issue for "rma.mv"? I know that these studies normally get "thrown out" for meta-analysis using "rma", however they have been included with "rma.mv", with comparatively low weights. 

My second question is related to weighting of studies and how this is determined using the default method with "rma.mv". I'm used to specifying a weighting system with "rma". I see there is an optional argument to specify weights with "rma.mv". Is this something I should consider doing, considering small samples sizes (2-20), and sparse outcomes?

Thanks in advance! 

Nadine Vogt

**Comment by wviechtb** [comment]
Dear Nadine,

The 'Issues' section of a GitHub repository is used for reporting potential bugs, suggesting enhancements to the software/package, and keeping track of development tasks. Your questions are about the use of `metafor` for particular analyses. A better place to ask those types of questions is on the R-sig-meta-analysis mailing list, which you can sign up for here:

https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis

So, please ask your questions there. I'll therefore close this issue.
