### ISSUE TITLE
Why do Random Effect and Fixed Effect models give exactly the same results

### ISSUE THREAD

**Issue by apzelic** [wviechtb/metafor#14]
Suppose I am working with the simple dataset attached (called "sutton_df.xlsx"
[sutton_df.xlsx](https://github.com/wviechtb/metafor/files/1510651/sutton_df.xlsx)
).  I am interested in calculating Risk Difference ("RD") for both a fixed effects model ("FEM") and a random effects model ("REM").  

I create two models as follows:

model.sutton.RD.FEM <- rma(measure = "RD", ai = tpos, ci=cpos, n1i = nt, n2i = nc, data = sutton_df, slab = Study.ID, method = "FE")

model.sutton.RD.REM <- rma(measure = "RD", ai = tpos, ci=cpos, n1i = nt, n2i = nc, data = sutton_df, slab = Study.ID, method = "REML")

A summary() of both of these models gives EXACTLY the same result for the intercept ($b) and all other parameters.  Further the REM shows zero heterogeneity.  And, the forest() plots give EXACTLY the same plots.

It seems to me that the REM and FEM results should be different, and that heterogeneity should not be zero in the REM.  Is there a bug here, or have I failed to understand the proper coding?

FWIW, calculating the odds ratio (via measure ="OR") also gives identical results for the FEM and REM, and once again zero heterogeneity in the REM.  Something seems amiss, but it could easily be with me.

Many thanks.

**Comment by wviechtb** [comment]
When tau^2 is estimated to be zero, the results for the RE model collapse to those of a FE model. That is exactly what should happen.

**Comment by apzelic** [comment]
I am getting a strange result for a simple model using metafor().  Suppose I am working with this dataset (called "BCG Vaccine.xlsx"). After reading this file into a dataframe called "bcg.dat"   I run the following:

bcg.res <- rma(ai = VaccineTB, bi = VaccineN, ci = ControlTB, di = ControlN, measure ="OR", method = "DL", data=bcg.dat)

And then I get the following very odd result with NEGATIVE Risk Ratio:

Random-Effects Model (k = 13; tau^2 estimator: DL)

tau^2 (estimated amount of total heterogeneity): 0.3187 (SE = 0.2326)
tau (square root of estimated tau^2 value):      0.5645
I^2 (total heterogeneity / total variability):   91.70%
H^2 (total variability / sampling variability):  12.04

Test for Heterogeneity: 
Q(df = 12) = 144.4960, p-val < .0001

Model Results:

estimate      se     zval    pval    ci.lb    ci.ub     
 -0.7117  0.1817  -3.9168  <.0001  -1.0678  -0.3556  ***



What in the world am I doing wrong?

My thanks again.


[BCG Vaccine.xlsx](https://github.com/wviechtb/metafor/files/1524160/BCG.Vaccine.xlsx)

**Comment by wviechtb** [comment]
Nothing. You are analyzing **log** risk/odds ratios.

But this is not the right place to ask such questions. I would suggest you sign up for the R-sig-meta-analysis mailing list (https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis).
