### ISSUE TITLE
Inconsistency between AIC and summary table ouput

### ISSUE THREAD

**Issue by kcolyvas** [wviechtb/metafor#15]
The attached code (and data file) illustrates a case in which there is an inconsistency between the importance of a variable added to the model as judged by AIC and the summary output. AIC says the variable matters, summary table says it does not.

I can't find a way to explain this, any suggestions?

Regards,
Kim

P.S. Thanks for developing and maintaining metafor. 
Good package and web site examples much better than most R packages for supporting users
[Final final data set_Hasintha.txt](https://github.com/wviechtb/metafor/files/1680619/Final.final.data.set_Hasintha.txt)

[metafor AIC inconsistent with summary table.R.txt](https://github.com/wviechtb/metafor/files/1680624/metafor.AIC.inconsistent.with.summary.table.R.txt)

**Comment by wviechtb** [comment]
The factor as a whole is highly significant:

`anova(f2, btt=5:6)`

and so is the contrast between levels `non-stabilised` and `stabilised`:

`anova(f2, L=c(0,0,0,0,1,-1))`

Please take a look at: http://www.metafor-project.org/doku.php/tips:testing_factors_lincoms
And maybe also: http://www.metafor-project.org/doku.php/tips:multiple_factors_interactions

**Comment by kcolyvas** [comment]
Dear Wolfgang,
Thank you for you feedback – I hadn’t learnt how to do the contrasts.

I realise now I was (incorrectly) assuming the SE’s for the two contrasts (in red below) would also similar for the other contrast. I am surprised that the SE dropped so much (to .0068) especially considering one of the groups in the comparison had the lowest sample size. My concern that led to sending my question was based on intuition and despite the stats you have helped me with something still doesn’t feel right. Such a small effect size (-.0973) is leading to what based on AIC was a very large improvement in the model.

Anyway,
Thank you again for your help and for writing such a good package,
Kim

Model Results:

                              estimate      se      zval    pval    ci.lb    ci.ub
intrcpt                         2.6984  0.4776    5.6495  <.0001   1.7623   3.6346  ***
rate                            0.0047  0.0011    4.2529  <.0001   0.0025   0.0068  ***
years                          -0.0674  0.0254   -2.6521  0.0080  -0.1173  -0.0176   **
depth.mid                      -0.1631  0.0033  -49.4873  <.0001  -0.1696  -0.1566  ***
biosolid.typenon-stabilised    -0.3092  0.4331   -0.7140  0.4752  -1.1582   0.5397
biosolid.typestabilised        -0.4065  0.4331   -0.9386  0.3480  -1.2555   0.4424


> table(data2$biosolid.type)



     co-compost non-stabilised      stabilised

             67             135              29



> anova(f2, L=rbind(c(0,0,0,0,1,0), c(0,0,0,0,0,1), c(0,0,0,0,-1,1)))

Hypotheses:
1:                             biosolid.typenon-stabilised  = 0
2:                                 biosolid.typestabilised  = 0
3: -biosolid.typenon-stabilised  + biosolid.typestabilised  = 0

Results:
   estimate     se     zval   pval
1:  -0.3092 0.4331  -0.7140 0.4752
2:  -0.4065 0.4331  -0.9386 0.3480
3:  -0.0973 0.0068 -14.2426 <.0001
