### ISSUE TITLE
Adding a constant to the means in the log transformed ratio of means

### ISSUE THREAD

**Issue by valentinitnelav** [wviechtb/metafor#17]
Dear @wviechtb,

I'm helping a colleague with implementing some R code for calculating effect sizes using  the log transformed ratio of means and I have the following issue with `metaphor::escalc()` function.

Can one add a constant to the means to "deal with" zero cases using `escalc()`? There seems to be an `add` and `to` arguments designed for this purpose, but I can't find a way to make them work. Here is what I mean:

```R
library(metafor)
m1i  <- 15.6
m2i  <- 12.2
n1i  <- 15
n2i  <- 20
sd1i <- 3.82
sd2i <- 3.22

# log response ratio
log(m1i) - log(m2i)
# [1] 0.245835
log(m1i + .5) - log(m2i + .5) # add a constant
# [1] 0.2372173

# variance of log response ratio
sd1i^2/(n1i * m1i^2) + sd2i^2/(n2i * m2i^2)
# [1] 0.007480549
sd1i^2/(n1i * (m1i + .5)^2) + sd2i^2/(n2i * (m2i + .5)^2) # add a constant
# [1] 0.006967255


lnR <- escalc(measure="ROM", vtype="LS", m1i=m1i, m2i=m2i, sd1i=sd1i, sd2i=sd2i, n1i=n1i, n2i=n2i)
lnRk <- escalc(measure="ROM", vtype="LS", add=0.5, to="all", m1i=m1i, m2i=m2i, sd1i=sd1i, sd2i=sd2i, n1i=n1i, n2i=n2i)
lnR; lnRk
#       yi     vi
# 1 0.2458 0.0075
#       yi     vi
# 1 0.2458 0.0075
all.equal(lnR, lnRk)
# [1] TRUE
```
I checked shortly the code behind `escalc()` and seems that the constant is not actually added when `measure = "ROM"` or other measures for *Quantitative Variables*, am I right? If that is so, then should I conclude that this was build purposely to discourage this practice of adding a constant for these measures?

Thank you for your amazing work on `metafor`! It is an impressive amount of thoughtful work and a great open source contribution!

Best,
Valentin

PS: This question is related to my post [here](https://stats.stackexchange.com/questions/335893/is-it-ok-to-add-a-constant-to-the-means-in-the-log-transformed-ratio-of-means).

**Comment by wviechtb** [comment]
The `add` and `to` arguments have no effect for `measure="ROM"`. `help(escalc)` indicates to which outcome measures these arguments apply.

I don't think adding a constant is an appropriate adjustment for `measure="ROM"`. Consider what happens as the sample sizes of the two groups increase. Then `m1i` and `m2i` converge to the true means and hence `log(m1i) - log(m2i)` converges to the true log ratio of means, but that won't be true for `log(m1i + .5) - log(m2i + .5)` (except when the true means are equal to each other).

**Comment by wviechtb** [comment]
Just as a final follow-up, I provided the same answer to your question on stats.stackexchange.com and also added a few additional thoughts there.
