### ISSUE TITLE
rma() produces different CIs for correlations than cor.test() or corr.test()

### ISSUE THREAD

**Issue by thisisnickb** [wviechtb/metafor#18]
Hello,

I'm having a bit of trouble with rma(), and I want to make sure I'm not crazy. I'm doing an internal meta-analysis of correlations, and the CI's that my core functions (cor.test and corr.test) are giving me don't match up with the ones from rma. I'm running the correlations, extracting the r's, n's, and se's, then feeding them into rma

Here's the dataframe (note the CIs):
![screen shot 2018-04-06 at 6 59 44 pm](https://user-images.githubusercontent.com/35079605/38447671-c42039a6-39cc-11e8-89f2-28152ab35fd2.png)

Here's the code that I'm feeding in:
rma(ri=Correlation, ni=n, data=TarPData, slab=Target, measure="COR")

And, weirdly, here's the forest plot (note that the CIs cross 1?)
![image](https://user-images.githubusercontent.com/35079605/38447688-f2d8b944-39cc-11e8-88a3-fc4ed008b38c.png)

Do you have any idea what's going on? Any idea how I can feed in the data in a way that matches the output from the correlation functions?

Thanks,

-Nick

**Comment by wviechtb** [comment]
You are calculating CIs using raw correlations and the SE of the raw correlations. `cor.test()` calculates the CI based on the Fisher transformation. See `help(cor.test)` (`"confidence interval is given based on Fisher's Z transform"`). If you want to do the same, then you should do:

    dat <- data.frame(ni=c(11,110), ri=c(.7436785,.8779966))
    dat <- escalc(measure="ZCOR", ri=ri, ni=ni, data=dat)
    summary(dat, transf=transf.ztor)

This yield:

       ni        ri     yi     vi    sei      zi  ci.lb  ci.ub 
    1  11 0.7436785 0.7437 0.1250 0.3536  2.7115 0.2596 0.9291 
    2 110 0.8779966 0.8780 0.0093 0.0967 14.1399 0.8267 0.9148

For the meta-analysis:

    res <- rma(yi, vi, data=dat)
    predict(res, transf=transf.ztor)
    forest(res, transf=transf.ztor)
