### ISSUE TITLE
R2 in a rma.mv model

### ISSUE THREAD

**Issue by nmolanog** [wviechtb/metafor#19]
Hello

I am fitting a rma.mv model and when trying to calculate R2 I got a negative value. It is quite strange to find that the variance of a null model is smaller than the variance of a model with moderators. I have opened a github repo where data and code is located. (https://github.com/nmolanog/issue_r2_metafor). I will appreciate if you can take a look at the small data and code.

Thank you

**Comment by wviechtb** [comment]
R^2 computed in this manner for these types of models is not guaranteed to yield a positive value. See, for example:

Lopez-Lopez, J. A., Marin-Martinez, F., Sanchez-Meca, J., Van den Noortgate, W., & Viechtbauer, W. (2014). Estimation of the predictive power of the model in mixed-effects meta-regression: A simulation study. _British Journal of Mathematical and Statistical Psychology, 67_(1), 30-48.

When R^2 is negative, it is typically truncated to 0.
