### ISSUE TITLE
Non sensible error message

### ISSUE THREAD

**Issue by Speldosa** [wviechtb/metafor#2]
The following R code halts and outputs an error message on line 3: 

    library("metafor")
    rma.mv(c(1,2,3), c(0.1,0.2,0.3)) # Works fine.
    rma.mv(c(1,2,3), c(0.1,0.2,0.3), sparse=TRUE) # Breaks down without any sensible error message.

This is the full error message:

    Error in `[<-`(`*tmp*`, upper.tri(Vlt), value = 0) : 
    error in evaluating the argument 'i' in selecting a method for function '[<-': Error in as.vector(data) : 
    no method for coercing this S4 class to a vector
    Calls: upper.tri ... as.matrix -> as.matrix.default -> array -> as.vector
    Calls: rma.mv -> [<-
    Execution halted

I don't know if I'm doing something wrong here (I encountered this problem when trying to run the sparse option on a much more complicated and larger data set). However, I believe that the error message should be caught by metafor and output something more sensible for the user (for example, I never called the function `as.vector(data)` myself).

**Comment by jamesfreinhardt** [comment]
Both commands i.e.:
    rma.mv(c(1,2,3), c(0.1,0.2,0.3))
    rma.mv(c(1,2,3), c(0.1,0.2,0.3), sparse=TRUE) 

produce identical answers for me.  

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] metafor_1.9-8 Matrix_1.2-2 

loaded via a namespace (and not attached):
[1] grid_3.2.2      lattice_0.20-33

**Comment by Speldosa** [comment]
@jamesfreinhardt Strange. I tried to run the commands separately in an R session in my terminal, and it went fine then. It's only when I run them as part of a .r script using the `Rscript` function in the terminal that things go wrong.

**Comment by Speldosa** [comment]
Ok, with the help of the following thread, I managed to solve my problem: http://stackoverflow.com/questions/19468506/rscript-could-not-find-function

Apparently, `Rscript` doesn't load the `methods` package by default, something that is needed here.

**Comment by wviechtb** [comment]
This has bitten me in the behind at least once or twice before. I'll consider adding a check.
