### ISSUE TITLE
Risk difference issue

### ISSUE THREAD

**Issue by britpenn** [wviechtb/metafor#22]
I am having an issue with the risk difference measure.  When the risk difference is something other than 1, the output is as I expected (the difference in proportions).  But when the risk difference is 1, I am getting something different.

For example, Here is a portion of my data:

upperleft lowerleft upperright lowerright
1      1.000      8.00     19.000      20.00
2      0.000      2.00      2.000       2.00
3      0.000      2.00      2.000       2.00
4      4.000      8.00      7.000      11.00
5      1.500      8.00      9.500      11.00
6      1.000      5.00     39.000      40.00
7      1.000      5.00     46.000      47.00

For lines 2 and 3, the risk difference should be 1 ((2/2)-(0/2)).

This is the code that I am using:

meta <- escalc(measure="RD", n1i=quadrants$lowerright, 
               n2i=quadrants$lowerleft, ai=quadrants$upperright,
               ci=quadrants$upperleft)

And here is the output:

       yi     vi
1  0.8250 0.0160
2  0.6667 0.0926
3  0.6667 0.0926
4  0.1364 0.0523
5  0.6761 0.0297
6  0.7750 0.0326
7  0.7787 0.0324

Any thoughts on why this may be happening?  

Thank you!

**Comment by wviechtb** [comment]
This happens due to the `add=1/2` adjustment that is used by default (see `help(escalc)` for details). You can switch off this behavior by setting `add=0` or `to="none"`.
