### ISSUE TITLE
Continuity correction only affects MH test (rma.mh), not estimates/CI

### ISSUE THREAD

**Issue by bjoernholzhauer** [wviechtb/metafor#24]
The continuity correction option in rma.mh seems to only affect the MH test, but not the estimates and confidence interval. Presumably it should affect all. This is for version 2.0-0.

```
library(metafor)

rma.mh(ai=c(0,0,2), bi=c(20,20,18), ci=c(0,2,4), di=c(20,18,16), measure="OR", correct=FALSE)
```

> Fixed-Effects Model (k = 3)
> 
> Test for Heterogeneity: 
> Q(df = 1) = 0.3092, p-val = 0.5782
> 
> Model Results (log scale):
> 
> estimate      se     zval    pval    ci.lb   ci.ub
>  -1.2528  0.8712  -1.4380  0.1504  -2.9602  0.4547
> 
> Model Results (OR scale):
> 
> estimate   ci.lb   ci.ub
>   0.2857  0.0518  1.5757
> 
> Cochran-Mantel-Haenszel Test:    CMH = 2.2286, df = 1, p-val = 0.1355
> Tarone's Test for Heterogeneity: X^2 = 0.8547, df = 1, p-val = 0.3552
```
rma.mh(ai=c(0,0,2), bi=c(20,20,18), ci=c(0,2,4), di=c(20,18,16), measure="OR", correct=TRUE, add=1/2, to="only0", drop00=FALSE)
```

> Fixed-Effects Model (k = 3)
> 
> Test for Heterogeneity: 
> Q(df = 2) = 0.6922, p-val = 0.7074
> 
> Model Results (log scale):
> 
> estimate      se     zval    pval    ci.lb   ci.ub
>  -1.2528  0.8712  -1.4380  0.1504  -2.9602  0.4547
> 
> Model Results (OR scale):
> 
> estimate   ci.lb   ci.ub
>   0.2857  0.0518  1.5757
> 
> Cochran-Mantel-Haenszel Test:    CMH = 1.2536, df = 1, p-val = 0.2629
> Tarone's Test for Heterogeneity: X^2 = 0.8547, df = 1, p-val = 0.3552

When I manually check what the estimate should be, I get:
```
mhor <- function(ai,bi,ci,di,correct=FALSE){
  if (correct==TRUE) {
    for (i in 1:length(ai)){
      if ((ai[i]==0) || (ci[i]==0)) {
        ai[i] = ai[i] + 0.5
        di[i] = di[i] + 0.5
        bi[i] = bi[i] + 0.5
        ci[i] = ci[i] + 0.5
      }
    }
  }
  return( sum( ai*di/(ai+bi+ci+di) ) / sum( bi*ci/(ai+bi+ci+di) ) )
}

mhor(ai=c(0,0,2), bi=c(20,20,18), ci=c(0,2,4), di=c(20,18,16), correct=FALSE)
```

> 0.2857143

```
mhor(ai=c(0,0,2), bi=c(20,20,18), ci=c(0,2,4), di=c(20,18,16), correct=TRUE)
```

> 0.3873085

**Comment by wviechtb** [comment]
The `correct` argument only applies to the Cochran-Mantel-Haenszel test. See `help(rma.mh)`:

    correct   logical indicating whether to apply a continuity correction when computing the Cochran-Mantel-Haenszel test statistic.

This continuity correction is not the same thing as the adjustment that is sometimes done to the cell counts. The `add` and `to` arguments are for that. Note that these arguments can take two values, the first is used in the calculation of the observed outcomes (e.g., for drawing forest plots) and the second is used when applying the Mantel-Haenszel method. So, it seems you want:

    rma.mh(ai=c(0,0,2),` bi=c(20,20,18), ci=c(0,2,4), di=c(20,18,16), measure="OR", correct=TRUE, add=c(1/2,1/2), to=c("only0","only0"), drop00=FALSE)

which gives

    Fixed-Effects Model (k = 3)
    
    Test for Heterogeneity: 
    Q(df = 2) = 0.4743, p-val = 0.7889
    
    Model Results (log scale):
    
    estimate      se     zval    pval    ci.lb   ci.ub 
     -0.9485  0.7266  -1.3054  0.1918  -2.3727  0.4756 
    
    Model Results (OR scale):
    
    estimate   ci.lb   ci.ub 
      0.3873  0.0932  1.6090 
    
    Cochran-Mantel-Haenszel Test:    CMH = 0.9907, df = 1, p-val = 0.3196
    Tarone's Test for Heterogeneity: X^2 = 0.5005, df = 2, p-val = 0.7786

Note that the `1/2` adjustment is really not needed when applying the MH method itself (except in some rare cases, but if those apply, then the MH method should probably not be used in the first place). On the other hand, the continuity correction for the CMH test statistic should by default be applied. So, the defaults are set to the recommended values.

**Comment by bjoernholzhauer** [comment]
That seems pretty weird. What I've always been taught is that the CMH test and the estimates/confidence intervals are both about equally affected by a continuity correction, either you do it for both or neither. 

Surely, the CIs would have the correct coverage exactly when the test keeps its level? That should be the case, because we base both on a normal approximation to the log-odds-ratio estimate and its variance, both of which can be calculated without a continuity correction (see e.g. chapter 15 of Modern Epidemiology 3rd edition by Rothman, Greenland and Lash), right?
