### ISSUE TITLE
meta vs metafor. Random effects options reversed? 

### ISSUE THREAD

**Issue by skanskan** [wviechtb/metafor#25]
Hello.

I'm trying the packages meta and metagen to perform a meta-analysis study.

With meta I write this and it provides both results, for fixed effects and mixed effects.
metagen(myX,mySD, sm="OR")

With metafor I must use two different calls:
rma(myX,sei=mySD, method="ML", measure="OR")  # Random effects.
rma(myX,sei=mySD, method="FE", measure="OR") # Fixed effects.

But strangely the "random-effects" option on metafor produces the same result than the fixed-effects option of meta and vice versa. I mean they are reversed.

What am I doing wrong?

**Comment by guido-s** [comment]
R function metagen() uses the DerSimonian-Laird method by default. You must use `metagen(..., method.tau = "ML")` for the ML estimator of the between-study variance which you are using in rma().

I do not understand your second point concerning the strange vice versa results. Could you please provide a small example for this.

**Comment by wviechtb** [comment]
Issue was resolved (and the "reversed" results are not reproducible).
