### ISSUE TITLE
Calculation of sample variance for partial-r to z seemingly doesn't make sense

### ISSUE THREAD

**Issue by the-sushi** [wviechtb/metafor#28]
For ZPCOR, you use `1/(ni-mi-1)`, and for ZCOR you use `1/(ni-3)`.  Presumably `mi` is the number of control variables (Aloe's *p* or Bonnet's *q*).  However, the zero-order partial *r* is identical to Pearson's *r*, so the variances must be identical but `1/(ni-0-1)`≠`1/(ni-3)`.  This is also visible in that for non-transformed PCOR you use `(1 - yi^2)^2 / (ni - mi - 1)` which would be identical to the typical `(1-yi^2)^2/ni-3` in the case of `mi=0`.

Not sure if I'm missing something but that seems incorrect.

Continuing with the assumption that `mi` is the number of control variables (*q*), Bonnet (2008) suggests that `1/(ni-3-mi)` can be used.

---

Bonett, D. G. (2008). Meta-Analytic Interval Estimation for Bivariate Correlations. *Psychological Methods*, 13(3), 173-181.

**Comment by wviechtb** [comment]
None of these equations are "correct" - they are all based on large-sample approximations.

The variance of ZPCOR simply follows from using (1-rp^2)^2 / (n-m-1) as the large sample approximation of the variance of a partial correlation coefficient (see Aloe, 2013, for references) and then applying the delta method.

The usual large sample approximation for the variance of COR is (1 - r^2)^2 / (n-1), although some might just divide by n. Based on this, the "correct" variance of ZCOR would be 1/(n-1) after applying the delta method. The 1/(n-3) equation for ZCOR just happens to be a better approximation for the variance of ZCOR that has been derived essentially empirically. But even better would be 1/(n-8/3) (see Hotelling, 1953), but nobody uses that.

**Comment by the-sushi** [comment]
Ah, I see. Thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
