### ISSUE TITLE
transf argument in confint.rma.uni

### ISSUE THREAD

**Issue by bwiernik** [wviechtb/metafor#29]
## Classification:

Bug Report

## Summary

In `confint.rma.uni`, the `transf` argument is only applied if `fixed==TRUE`. If fixed is false, results are returned in the original untransformed metric.

## Reproducible Example (if applicable)

res <- rma(measure="RR", ai=tpos, bi=tneg, ci=cpos, di=cneg, data=dat.bcg)
confint(res)
confint(res, transf = exp) # Same result

## sessionInfo()

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] metafor_2.1-0 Matrix_1.2-17

loaded via a namespace (and not attached):
[1] compiler_3.5.3  tools_3.5.3     nlme_3.1-139    grid_3.5.3      lattice_0.20-38
```

**Comment by wviechtb** [comment]
That's how it is supposed to be. The `transf` argument only applies to the fixed effects (it can be "used to transform the model coefficients and interval bounds"; see `help(confint.rma)`). I could write "corresponding interval bounds" if this might clarify things further (so it is clear that this only pertains to the interval bounds of the model coefficients).

**Comment by bwiernik** [comment]
I see, I didn't read the docs carefully and assumed that it was applying integration or Taylor Series transformations to tau^2 as well.

**Comment by wviechtb** [comment]
Do you have a particular use case in mind for this? I don't see how transforming tau^2 (or tau or I^2 or H^2) would be useful.

**Comment by bwiernik** [comment]
For example, to report the random effects standard deviation in the same effect size metric as the mean effect size as an Indicator of the absolute magnitude of heterogeneity. Yes, you would general construct credibility intervals in the untransformed metric and transform the endpoints, but examination of the magnitude of tau is a useful direct consideration of the amount of heterogeneity.

**Comment by bwiernik** [comment]
So if I do my analysis in z, but want to report results in r, for example.

**Comment by wviechtb** [comment]
I see. I might consider adding this. For now, the easiest thing to do is to compute a prediction/credibility interval and back-transform the bounds. That gives very similar information (in fact, might be easier to interpret for many than giving tau in the back-transformed metric). I think I'll close this issue now, because we are venturing away from the original report. Happy to discuss this further on the mailing list.
