### ISSUE TITLE
improve error on nrow(mods)!=k

### ISSUE THREAD

**Issue by tbates** [wviechtb/metafor#30]
It would be useful if the error below (I think it's finding problem with mods, but really not sure... everything seems fine) had an extra message say what value nrow(mods) and k took. so

> Number of rows of the model matrix (nrow(mods) does not match length of the outcome vector (k).")). I got 3 rows in the mod column, but detected k=4 studies

Also, the error message includes the stop function (i.e., the error parsing code itself generates an error.

```R
betas = c(US=.001 , AU=.0757, IL=.0020)
SEs   = c(US=.0036, AU=.0276, IL=.0131)
mod  = c(US="SCAN", AU="UK", IL="SCAN")
ma = metafor::rma(yi=betas, sei = SEs, slab = slab, mods= factor(mod))

```
> Error in if (!is.null(mods) && (nrow(mods) != k)) stop(mstyle$stop("Number of rows of the model matrix does not match length of the outcome vector.")) : 
  missing value where TRUE/FALSE needed

`packageVersion("metafor")  ‘2.1.0’`

**Comment by tbates** [comment]
Works fine with `mods` as a formula, e.g., 
```R
rma(..., mods = ~ mod)
```
so looks like mods either doesn't take a vector input and/or should check if it's input is a formula.

Love the package!!

**Comment by wviechtb** [comment]
Hi Tim,

If you don't specify a formula for `mods`, then you should specify a design matrix. Actually, `mods` handles a vector input in that case just fine (and converts this to a matrix), so this will work:

    mod <- 1:3
    ma <- rma(yi=betas, sei=SEs, mods=mod)

But if you don't specify a formula, then you don't get access to formula syntax, so things like `mods = factor(mod)` shouldn't be expected to work (instead, you would have to encode the factor yourself). The reason why that error is thrown is that I never expected somebody to pass a factor variable as a design matrix to `mods` (what would happen is that the integer representations of the factor levels are then analyzed as a numeric moderator, which makes no sense). I might add a check for that, but in general, the use of formulas is highly encouraged (and much more flexible).

Also, adding more info to the error message (of this type) is a good suggestion that I might follow up on (but then throughout the entire package, so this is going to be a more extensive endeavor).

**Comment by tbates** [comment]
Hi Wolfgang,
Figured out that `mods = formula` is normal!

Error message tweaks would be great! Probably one at a time is fine for users, who hopefully will appreciate the one they see without begrudging the one that they didn't :-)

**Comment by wviechtb** [comment]
I just pushed an update to the repo that provides more informative error messages for various dimension mismatches. That could be further expanded on in the future, but for now I consider this enhancement as done.

**Comment by tbates** [comment]
Thanks so much Wolfgang! Love the package
