### ISSUE TITLE
rma.mv & rma yield different results (rma works, rma.mv gives an error) for identical formulas *when loading data from a DTA file  created by haven*

### ISSUE THREAD

**Issue by setgree** [wviechtb/metafor#31]
## Update: 
The issue was solved when by loading the identical dataset via a `csv` file rather than a `dta` file.

## Classification:

Bug Report

## Summary
* I am working on a large-ish (1200 rows x 70 columns) meta-analysis. I am looking to meta-analyze the data with within-paper effects (we have a variable called unique_paper_id -- it's about 1200 from 303 separate papers).
* When I run `res <- metafor::rma.uni(d, var_d, data = dat); print(res, digits=3)`, I get

```
Random-Effects Model (k = 1231; tau^2 estimator: REML)
tau^2 (estimated amount of total heterogeneity): 0.136 (SE = 0.007)
```
and so on.

* But when I run `res2 <- metafor::rma.mv(d, var_d, data = dat)`, I get
```
Error in if (V0 || is.vector(V) || nrow(V) == 1L || ncol(V) == 1L) { : 
  missing value where TRUE/FALSE needed
```
I'm afraid I am not sure where to begin with this. The documentation (http://www.metafor-project.org/doku.php/tips:rma.uni_vs_rma.mv) says:
>  one can also use the rma.mv() function to fit the same models as the rma.uni() function, since those models are really just special cases of the more general models handled by the rma.mv() function 

and 
> The same model can be fitted to these data using the rma.mv() function. 

I am also not sure what will suffice for a reproducible minimal example, as I am not at liberty to share the data broadly -- though, possibly, I may be able to share a dropbox link with someone via private correspondence --  and I failed to reproduce this with any of the built-in datasets. 

So my main question is: is this something you have seen before? 

Thanks in advance for your help! 

### Session Info:
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.4   metafor_2.1-0 Matrix_1.2-18 haven_2.2.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          compiler_3.6.0      pillar_1.4.3        nloptr_1.2.2       
 [5] forcats_0.4.0       tools_3.6.0         boot_1.3-24         lme4_1.1-21        
 [9] tibble_2.1.3        nlme_3.1-144        lattice_0.20-40     pkgconfig_2.0.3    
[13] rlang_0.4.4         rstudioapi_0.11     yaml_2.2.1          mvtnorm_1.0-12     
[17] vctrs_0.2.3         hms_0.5.3           stats4_3.6.0        grid_3.6.0         
[21] tidyselect_1.0.0    glue_1.3.1          R6_2.4.1            bdsmatrix_1.3-4    
[25] minqa_1.2.4         readr_1.3.1         purrr_0.3.3         magrittr_1.5       
[29] metaplus_0.7-11     MASS_7.3-51.5       splines_3.6.0       assertthat_0.2.1   
[33] fastGHQuad_1.0      bbmle_1.0.23.1      numDeriv_2016.8-1.1 crayon_1.3.4       
```

### Brief update:
I tried this with the development version of metafor `(remotes::install_github('wviechtb/metafor')` and the error persists with metafor version `2.2-8`

**Comment by wviechtb** [comment]
Thanks for the clear bug report. I was going to ask you to try this with the devel version, but you also checked that, too. Thanks! And to answer your main question: No, I haven't seen this before.

Just a small side-note: `rma.mv(d, var_d, data = dat)` would not reproduce `rma.uni(d, var_d, data = dat)` as you would have to add random effects in `rma.mv()`, but that's not relevant here (`rma.mv()` should work).

I see that you have `haven` attached. How are you importing the data? Also, can you show me `class(dat)`, `class(dat$d)`, and `class(dat$var_d)`? Also, instead of the full dataset, how about `head(dat$d)`, `head(dat$var_d)`, or both together with `head(dat[,c("d", "var_d")])`?

**Comment by setgree** [comment]
Hi @wviechtb , thanks for the response.

The data file is a DTA, and I'm reading it in via `haven::read_dta()`.  I've removed all DTAs in the relevant columns via
```

Regaridng

**Comment by setgree** [comment]
Hi @wviechtb , thanks for the response.

The data file is a DTA, and I'm reading it in via `haven::read_dta()`.  I've removed all DTAs in the relevant columns via
```
dat <- dat %>%
  filter(!is.na(d)) %>%
  filter(!is.na(st_err_d)) %>%
  filter(!is.na(var_d))
```
(I am sure there is a more elegant way to do that but I personally like verbose, clear code.)

Regarding the additional info:

```
> class(dat)
[1] "tbl_df"     "tbl"        "data.frame"
> class(dat$d)
[1] "numeric"
> class(dat$var_d)
[1] "numeric"
> head(dat[,c("d", "var_d")])
# A tibble: 6 x 2
      d var_d
  <dbl> <dbl>
1 1.04  0.052
2 1.07  0.053
3 0.704 0.072
4 0.727 0.073
5 0.457 0.044
6 0     0.043
```

Thanks again!

**Comment by setgree** [comment]
### Good news!
Problem is solved when I use a `.csv file rather than `.dta` (which had been created with `haven::write_dta`). I saved the exact same data frame to a `.csv` file and now everything works fine. Thanks for the suggestion, @wviechtb!

So there is something about how `haven` saves files that does not play nicely with `metafor`. I'll update my original content and the title of the issue to reflect this (and if you want to close it as out of scope, that's of course fine by me).

**Comment by wviechtb** [comment]
Thanks for the updates and glad to hear that you have in principle a working solution. Of course, I still would like to figure out what causes the problem. My initial guess was that it is related to `haven` creating tibbles, but

```r
library(metafor)
library(tibble)
dat <- escalc(measure="RR", ai=tpos, bi=tneg, ci=cpos, di=cneg, data=dat.bcg)
dat <- as_tibble(dat)
rma.mv(yi, vi, data=dat)
```

works fine. I'll try to see what happens when actually using `read_dta()`, but one more thing I am wondering about: What happens if you read the data in as before, but then use `dat <- as.data.frame(dat)` before fitting the model? Does it work then?

**Comment by wviechtb** [comment]
I figured it out. It has nothing to do with tibbles per se, it's just that there is some kind of attribute attached to `var_d` when reading in the data with `haven` and this leads to a problem. To illustrate:
```r
library(metafor)
dat <- escalc(measure="RR", ai=tpos, bi=tneg, ci=cpos, di=cneg, data=dat.bcg)
rma.mv(yi, vi, data=dat)
```
works. But:
```r
attr(dat$vi, "foo") <- "bar"
rma.mv(yi, vi, data=dat)
```
causes the error. I'll figure out how to fix this.
