### ISSUE TITLE
Add a warning about z-tests with few degrees of freedom

### ISSUE THREAD

**Issue by MetaEntropy** [wviechtb/metafor#36]
## Classification:

Enhancement Suggestion

## Summary

Random-effects meta-analysis can be performed with rma(), defaulting to z-test even if the number of degrees of freedom is very low, leading to highly biased P-values without warning.
Use of test="knha" should be highly encouraged.

## Reproducible Example

```r
rma(c(1,3),c(0.5, 0.5))
```

Observed behavior : no warning
Expected behavior : warning

## Notes

I have a patch providing relevant warning messages such as:
z-test approximation is very poor with 1 degrees of freedom.
At 5% significance level, type I error rate raises to 30%
Please, use test="knha" to fix that issue

[warning.patch.txt](https://github.com/wviechtb/metafor/files/5079517/warning.patch.txt)

Do you want a pull request?

## sessionInfo()

Post output of `sessionInfo()` below:

```
R Under development (unstable) (2020-08-13 r79017)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] metafor_2.4-0 Matrix_1.2-18

loaded via a namespace (and not attached):
[1] compiler_4.1.0  tools_4.1.0     nlme_3.1-148    grid_4.1.0      lattice_0.20-41
```

**Comment by wviechtb** [comment]
Thanks for the suggestion. While I generally agree that the K&H method should often be used when it is not, I would prefer not to implement this for two reasons.

First of all, the degree of inflation depends on the amount of heterogeneity. If tau^2 is close to zero, then the standard Wald-type test does not actually have an inflated Type I error rate. At the same time, the power of the K&H method can be considerably lower than that of the standard Wald-type test (even in situations where both tests have adequate control of the Type I error rate). So, the warning that is being issued by the patch isn't true in general.

Also, it is a bit too prescriptive for my taste. I generally don't make recommendations via the package what users should or should not do. Again, while I don't disagree that the K&H method should often be used (and maybe it would have been better to make the K&H method the default), I don't think this should be done via warning messages in the software.

**Comment by MetaEntropy** [comment]
Le 18/08/2020 à 13:31, Wolfgang Viechtbauer a écrit :
>
> Thanks for the suggestion. While I generally agree that the K&H method 
> should often be used when it is not, I would prefer not to implement 
> this for two reasons.
>
> First of all, the degree of inflation depends on the amount of 
> heterogeneity. If tau^2 is close to zero, then the standard Wald-type 
> test does not actually have an inflated Type I error rate. At the same 
> time, the power of the K&H method can be considerably lower than that 
> of the standard Wald-type test (even in situations where both tests 
> have adequate control of the Type I error rate). So, the warning that 
> is being issued by the patch isn't true in general.
>

Ok. I had implicitly assumed that studies very large, making the 
heterogeneity high, but that is not always the case.

> Also, it is a bit too prescriptive for my taste. I generally don't 
> make recommendations via the package what users should or should not 
> do. Again, while I don't disagree that the K&H method should often be 
> used (and maybe it would have been better to make the K&H method the 
> default), I don't think this should be done via warning messages in 
> the software.
>
Ok.
