### ISSUE TITLE
Factor being transformed into numeric - Enhancement Suggestion

### ISSUE THREAD

**Issue by patarol** [wviechtb/metafor#38]
I'm using `rma.mv` function for perform a model. I have a variable called `climate` that's a binary and it's a `factor`, wit the levels `Tropical` and `Temperate`.
When I run the model (with interactions) the `summary` function  from the model output object, it returns something like that (hypothetical output):

``` 
Multivariate Meta-Analysis Model (k = 229; method: ML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor 
sigma^2    0.1311  0.3621     45     no  id_group 

Test for Residual Heterogeneity:
QE(df = 223) = 548.9318, p-val < .0001

Test of Moderators (coefficients 1:6):
QM(df = 6) = 64.0154, p-val < .0001

Model Results:

                      estimate      se     zval    pval    ci.lb    ci.ub  
crop1                      -0.0514  0.1173  -0.4378  0.6616  -0.2814   0.1786      
climate1                 -0.2151  0.0781  -2.7553  0.0059  -0.3681  -0.0621   ** 
crop1: climate1      -0.1491  0.0781  -1.9099  0.0561  -0.3021   0.0039    .  

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

So, my question is, what is actually `climate1`? In my example it would be `Tropical` or `Temperate`. I've tried change the variable `climate` to numeric and see which one is replaced with `1` and which one is replaced with `2` (from `as.numeric.factor` `S3` function), however if I change the order of the label, it returns the same summary statistics. 
I'd like to know how to identify which `climate1` is referring to: `Tropical` or `Temperate`.

Thank you, best

**Comment by wviechtb** [comment]
Dear Luciano, issues at GitHub are for bug reports or suggestions for improving the package, but your question is really a general support question. Those are better asked here: https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis

**Comment by patarol** [comment]
Actually you could add a factor instead of that number. It's impossible to now what is that. 
If you're not able to answer it, I'll ask in another platform.
Thank you anyway

**Comment by wviechtb** [comment]
I can answer this, but not here. Please ask on the mailing list and I would be happy to respond.
