### ISSUE TITLE
meta-regression with beta likelihood

### ISSUE THREAD

**Issue by MilaniC** [wviechtb/metafor#4]
I was wondering if there are plans to add meta-regression modelling capacity with Beta likelihood for soft bound (0,1) response data. Such as rates or survival probability estimates (with estimates of precision) derived from capture-mark-recapture studies. Unlike in the Gaussian likelihood were it is possible and desirable to fix the residual variance to 1, it is not clear to me if that concept is still applicable for the Beta likelihood regression (would this be the same as fixing the dispersion parameter). Just some ponderings!

**Comment by wviechtb** [comment]
Isn't this something you can do with the [betareg](https://cran.r-project.org/package=betareg) package?

**Comment by MilaniC** [comment]
Yes indeed. And we have done just that. But the query is whether the dispersion parameter should be fixed (perhaps = zero). And that was the crux of the query and hence wondering if you had considered that if you were going to add Beta likelihood function to metafor.

**Comment by wviechtb** [comment]
The issue with the residual variance in a Gaussian model is something entirely different than the dispersion parameter in a beta distribution, so I don't see what this is supposed to accomplish. It would make some sense to let the precision parameter (phi) be a function of the precision of the estimates. You can actually do this with betareg -- it allows for regressors for the precision parameter.

**Comment by MilaniC** [comment]
Yes thank you. That is also what we have done. it is reassuring that this approach does in fact made sense.
