### ISSUE TITLE
rcalc function

### ISSUE THREAD

**Issue by carolaruizh** [wviechtb/metafor#40]
## Classification:

Bug Report

## Summary

The rcalc function works with the dataset from the example dat.craft2003 but does not work with other datasets. 

## Reproducible Example (if applicable)

When running the example provided with the package from the dat.craft2003 it runs well and then it can be used by he rma.mv function.
Example from the package: 
tmp <- rcalc(ri ~ var1 + var2 | study, ni=ni, data=dat)
V <- tmp$V
dat <- tmp$dat

However, when using other datasets and reproducing the same process, at the moment of doing the last step, (dat<-tmp$dat) this returns dat as empty. The previous two steps seem to work well. 

I tried it with different datasets and even with one that resembled exactly the Craft2003 one from a csv file and the same problem occurred. 

I understand that this might be a consequence of the function being under development and I apologise if that is the case. 

Best regards,

**Comment by wviechtb** [comment]
Please provide a reproducible example. Here is one that works using a different dataset:

    library(metafor)
    
    mydat <- data.frame(
       id  = c(1,1,1,2,2,3),
       x   = c(1,1,2,1,1,2),
       y   = c(2,3,3,2,3,3),
       cor = rep(.30, 6),
       N   = rep(40, 6))
    
    rcalc(cor ~ x + y | id, ni=N, data=mydat)

**Comment by carolaruizh** [comment]
Dear Dr. Viechtbauer,

Thanks for such a prompt response.

I was trying to reproduce the four lines of code from this example from the
function (which runs without a problem).

dat <- dat.craft2003
tmp <- rcalc(ri ~ var1 + var2 | study, ni=ni, data=dat)
V <- tmp$V
dat <- tmp$dat

However, if I try the following, everything runs until the last line,
which  gives a Null result for mydat.

mydat <- data.frame(
  id  = c(1,1,1,2,2,3),
  x   = c(1,1,2,1,1,2),
  y   = c(2,3,3,2,3,3),
  cor = rep(.30, 6),
  N   = rep(40, 6))

tmp<-rcalc(cor ~ x + y | id, ni=N, data=mydat)
V <- tmp$V
mydat <- tmp$mydat

The purpose of the last two lines was to use the output within the rma.mv
function, which I am assuming I could workaround the last two steps and set
V=tmp$V and data=tmp$mydat

Thanks again for such a prompt response.
Best regards,
Carola

**Comment by wviechtb** [comment]
`tmp` does not contain an element called `mydat`. Look at (i.e., print) `tmp` to see what it contains.
