### ISSUE TITLE
Standard Error of Mean or Standard Deviation need to input in rma.uni as sei=

### ISSUE THREAD

**Issue by wahyuk** [wviechtb/metafor#49]
## Classification:

(Pick one of: Bug Report, Feature Request, Enhancement Suggestion)

General questions about the use of the metafor package should not be asked here, but on the `r-sig-meta-analysis` mailing list (https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis). Anything posted here should really be related to the *development* of the package (including potential bug reports).

## Summary

Summary of the problem.

## Reproducible Example (if applicable)

If applicable, please provide a minimal and fully reproducible example. Remove any superfluous code that is not pertinent to the issue at hand and provide a small dataset together with the code so that it can actually be run (the `dput()` function is extremely useful for this; or use one of the datasets that comes with the metafor package). See also:

- http://adv-r.had.co.nz/Reproducibility.html
- https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
- https://cran.r-project.org/web/packages/reprex/vignettes/reprex-dos-and-donts.html

```r
# use this for posting code (if applicable)
```

```
# use this for posting output (if applicable)
```

## Notes

Describe any debugging steps you've taken yourself. If you've found a workaround, please provide it here.

## sessionInfo()

Post output of `sessionInfo()` below:

```
# put output here
```

**Comment by wviechtb** [comment]
This is not a bug report or related to the development of the package. Please actually *read* what it says in the issue report ("General questions about the use of the metafor package should not be asked here, but ...").
