### ISSUE TITLE
measure = "SMDC"

### ISSUE THREAD

**Issue by bwiernik** [wviechtb/metafor#58]
## Classification:

Enhancement Suggestion

## Summary

Could `measure = "SMDC"` or similar be added for standardized mean differences using the control group SD as the reference (Glass's Delta), rather than the pooled (`measure = "SMD"`) or averaged (`measure = "SMDH"`) SD?

**Comment by wviechtb** [comment]
Done in c13cede. It's called `SMD1`. The `sd2i` value is used for standardizing.

**Comment by bwiernik** [comment]
Awesome! Thank you!
