### ISSUE TITLE
Cannot load function conv.wald()

### ISSUE THREAD

**Issue by jessistanbul** [wviechtb/metafor#70]
## Classification: Bug Report

General questions about the use of the metafor package should not be asked here, but on the `r-sig-meta-analysis` mailing list (https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis). Anything posted here should really be related to the *development* of the package (including potential bug reports).

## Summary

I couldn't find the function conv.wald()
I also tried to search it in R and got the following message:
> ?conv.wald()
Error in .helpForCall(topicExpr, parent.frame()) : 
  no methods for ‘conv.wald’ and no documentation for it as a function

## Reproducible Example (if applicable)

If applicable, please provide a minimal and fully reproducible example. Remove any superfluous code that is not pertinent to the issue at hand and provide a small dataset together with the code so that it can actually be run (the `dput()` function is extremely useful for this; or use one of the datasets that comes with the metafor package). See also:

- http://adv-r.had.co.nz/Reproducibility.html
- https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
- https://cran.r-project.org/web/packages/reprex/vignettes/reprex-dos-and-donts.html

```r
# use this for posting code (if applicable)
```

```
# use this for posting output (if applicable)
```

## Notes

Describe any debugging steps you've taken yourself. If you've found a workaround, please provide it here.

## sessionInfo()

Post output of `sessionInfo()` below:

```
# put output here
```

**Comment by wviechtb** [comment]
Since you did not post the `sessionInfo()` (as asked for in the instructions above), I can only guess that you do not have the current version (4.0-0) of the metafor package installed. So please upgrade and then see if it works.

**Comment by jessistanbul** [comment]
Hi wviechtb, 

Thanks! I upgraded my R and now it works. However, I encountered another problem with conv.wald function. I am going to start a new thread on that.
