### ISSUE TITLE
Adding 'author and year' to studies that used conv.wald() in order to merge with studies that used escalc() - for generating forest plot

### ISSUE THREAD

**Issue by jessistanbul** [wviechtb/metafor#72]
## Classification: Bug Report / Feature Request

(Pick one of: Bug Report, Feature Request, Enhancement Suggestion)

General questions about the use of the metafor package should not be asked here, but on the `r-sig-meta-analysis` mailing list (https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis). Anything posted here should really be related to the *development* of the package (including potential bug reports).

## Summary

Hi developer, 

I am trying to use escalc() for studies that reported 2*2 table and conv.wald() for studies that reported OR and 95% CI. I was able to run these functions smoothly and got effect size and variance estimates (yi and vi). The next step is to generate forest plot to visualize the results. Particularly, I would like to add 'author and year' in the forest plot to distinguish among studies. I was able to annotate this in the escalc function. However, **how can I attach these two the studies that used conv.wald()?** The resulted forest plot, after running escalc() and conv.wald() did not show the author and year information properly. Please find below the codes to reproduce the plot (below). Kindly note that I specified author and year in the escalc function.

macro.ovwt.m<-escalc(measure='OR',ai=t1d1,bi=t1d0,ci=t0d1,di=t0d0,data =macro.ovwt,slab=paste(author, year, sep=", "))

## Reproducible Example (if applicable)

If applicable, please provide a minimal and fully reproducible example. Remove any superfluous code that is not pertinent to the issue at hand and provide a small dataset together with the code so that it can actually be run (the `dput()` function is extremely useful for this; or use one of the datasets that comes with the metafor package). See also:

- http://adv-r.had.co.nz/Reproducibility.html
- https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
- https://cran.r-project.org/web/packages/reprex/vignettes/reprex-dos-and-donts.html

```r
# use this for posting code (if applicable)
macro.ovwt<-structure(list(y = c("macrosomia", "macrosomia", "macrosomia", 
"macrosomia", "macrosomia", "macrosomia", "macrosomia", "macrosomia", 
"macrosomia", "macrosomia", "macrosomia", "macrosomia", "macrosomia", 
"macrosomia"), x = c("ovwt", "ovwt", "ovwt", "ovwt", "ovwt", 
"ovwt", "ovwt", "ovwt", "ovwt", "ovwt", "ovwt", "ovwt", "ovwt", 
"ovwt"), study.id = c(1116L, 1993L, 4385L, 5029L, 5850L, 6069L, 
3776L, 2647L, 6071L, 3934L, 3533L, 5001L, 5534L, 3836L), author = c("Sun", 
"Nobumoto", "Leng", "Ouzounian", "Tavares", "Wang", "Hashemipour", 
"Barquiel", "Wang", "Ijas", "Fuka", "Olmos", "Scifres", "Hilden"
), country = c("China", "Japan", "China", "USA", "Brazil", "China", 
"Iran", "Spain", "China", "Finland", "Fiji", "Chile", "USA", 
"Sweden"), year = c(2014L, 2015L, 2015L, 2011L, 2019L, 2015L, 
2018L, 2018L, 2018L, 2019L, 2020L, 2012L, 2015L, 2016L), ntot = c(1310L, 
491L, 1263L, 1502L, 116L, 587L, 305L, 3284L, 601L, 5680L, 235L, 
251L, 1344L, 13057L), cont_expo = c(NA, NA, 1L, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA), sensitivity = c(NA, 1L, NA, NA, 
NA, 1L, NA, NA, NA, NA, NA, 1L, NA, NA), n_expo = c(3L, 2L, 3L, 
3L, 3L, 2L, 3L, 3L, 3L, 3L, 3L, 2L, NA, NA), expo_cutoff = c("24, 24-28, 28+ (obese)", 
"25, 25+", "24, 24-28, 28+", "25, 25-30, 30+", "25, 25-30, 30+", 
"25, 25+", "25, 25-30, 30+", "25, 25-30, 30+", "24, 24-28, 28+", 
"25, 25-30, 30+", "25, 25-30, 30+", "25, 25+", "25, 25-30, 30+", 
"25, 25-30, 30+"), updated_ntot = c(1132L, 491L, NA, 1023L, 67L, 
587L, 246L, 2921L, 502L, 3643L, 75L, 251L, 707L, 8086L), adjusted_or = c(0L, 
0L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L), t0d1 = c(7L, 
3L, NA, NA, 0L, 30L, 7L, 56L, 31L, 48L, NA, 6L, NA, 169L), t0d0 = c(762L, 
406L, NA, NA, 32L, 443L, 56L, 2100L, 363L, 1711L, NA, 119L, NA, 
3945L), control = c(769L, 409L, NA, NA, 32L, 473L, 63L, 2156L, 
394L, 1759L, NA, 125L, NA, 4114L), t1d1 = c(80L, 1L, NA, NA, 
5L, 19L, 35L, 24L, 9L, 83L, NA, 15L, NA, 274L), t1d0 = c(283L, 
81L, NA, NA, 30L, 95L, 148L, 741L, 99L, 1801L, NA, 111L, NA, 
3698L), treat = c(363L, 82L, NA, NA, 35L, 114L, 183L, 765L, 108L, 
1884L, NA, 126L, NA, 3972L), oddsratio = c(1.64, 1.67, 2.06, 
1.16, NA, NA, NA, NA, NA, NA, 0.93, NA, 1.54, NA), lower = c(1.14, 
0.17, 1.5, 0.75, NA, NA, NA, NA, NA, NA, 0.21, NA, 0.74, NA), 
    upper = c(2.36, 16.3, 2.84, 1.82, NA, NA, NA, NA, NA, NA, 
    4.12, NA, 3.17, NA)), row.names = c(NA, 14L), class = "data.frame")


## Overweight vs. Normal, overall
macro.ovwt<-subset(macrosomia,x=='ovwt')
names(macro.ovwt)[which(names(macro.ovwt) == "x")] <- "xvar"

macro.ovwt.m<-escalc(measure='OR',ai=t1d1,bi=t1d0,ci=t0d1,di=t0d0,data =macro.ovwt,slab=paste(author, year, sep=", "))
macro.ovwt.m<-conv.wald(out=oddsratio, ci.lb=lower, ci.ub=upper, data=macro.ovwt.m,transf=log)

res.macro.ovwt<-rma(yi,vi,data=macro.ovwt.m,method='DL')

forest(res.macro.ovwt, atransf=exp, at=log(c(.05, .25, 1, 4)), xlim=c(-16,6),
       ilab=cbind(macro.ovwt.m$country, macro.ovwt.m$updated_ntot,  macro.ovwt.m$ref, macro.ovwt.m$exposed), 
       ilab.xpos=c(-9.5,-8,-6,-4.5),
       cex=.75, header="Author(s) and Year", mlab="")


# use this for posting output (if applicable)
![image](https://user-images.githubusercontent.com/54902459/235043959-92d62010-7a75-419f-b4f9-a3e2e1706fcd.png)

## Notes

Describe any debugging steps you've taken yourself. If you've found a workaround, please provide it here.

## sessionInfo()

Post output of `sessionInfo()` below:

```
# put output here
```

**Comment by wviechtb** [comment]
You can also pass the `slab` information to `rma()` (i.e., use `res.macro.ovwt <- rma(yi, vi, data=macro.ovwt.m, method='DL', slab=paste(author, year, sep=", "))`).
