### ISSUE TITLE
Shouldn't variance be the standard deviation squared?

### ISSUE THREAD

**Issue by manellopez13** [wviechtb/metafor#73]
## Classification:

Bug Report

## Summary

I'm using escalc with measure = "MN", so I provide the mean, the standard deviation and the number of samples (mi, sdi and ni) as arguments. However, the results show how the variances (vi) are actually the squares of the standard errors (sdi / sqrt(ni)), not the standard deviations. I can see the [line of code 1787 of escalc.r](https://github.com/cran/metafor/blob/d62321ea2dd2c98f98880a0f0da46ff9c1f6810e/R/escalc.r#L1787) where this calculation is performed.

I feel like this is not correct, as everywhere I read about the Q and I^2 statistics, I see sigma^2 denoted as variance, not variance of the mean.

**Comment by wviechtb** [comment]
No, this is correct. For the meta-analysis, we need the sampling variances (i.e., the square of the standard errors).
