### ISSUE TITLE
Prevent archival from CRAN

### ISSUE THREAD

**Issue by psolymos** [wviechtb/metafor#82]
## Classification:

Enhancement Suggestion

## Summary

As per CRAN email:

> package metafor is now scheduled for archival on 2024-04-07, and archiving this will necessitate also archiving its CRAN strong reverse dependencies.

CRAN check shows NOTEs: `Packages suggested but not available for checking: 'Rcgmin', 'Rvmmin'` which seem to be already addressed in https://github.com/wviechtb/metafor/commit/720c8bfd7e6119fe77843b7fc98d5e65358a0214

Would it be possible to submit an update to CRAN by the deadline?

Thank you!

**Comment by GabrielHoffman** [comment]
Hi Wolfgang, 
Thanks for the great package.  Just emphasizing the importance of this update since dependencies `Rcgmin` and `Rvmmin` fail CRAN checks and so cause `metafor` to fail also.  This means that any package in CRAN or Bioconductor that depends on `metafor` now also fails.  

Best, 
Gabriel

**Comment by wviechtb** [comment]
Apologies for the hassle. Will get this fixed asap.

**Comment by wviechtb** [comment]
Just submitted a new version to CRAN. Hopefully this one will go through without problems and then this issue can be closed.

**Comment by psolymos** [comment]
Thank you @wviechtb !

**Comment by wviechtb** [comment]
New version on CRAN, so this is resolved.
