### ISSUE TITLE
Is this R script correct for conducting a meta-analysis of AOR for hypertension prevalence?

### ISSUE THREAD

**Issue by sancho2023** [wviechtb/metafor#84]
![Capturar](https://github.com/user-attachments/assets/b4566930-0a81-46e8-b98d-7187b2bc4486)
**Question:**

I am conducting a meta-analysis and meta-regression to calculate the **pooled adjusted odds ratio (AOR)** and **I² with the p-value** for variables associated with hypertension prevalence. I have a dataset with the following columns:

-     **study_id:** Study identifier
-     **AOR:** Adjusted odds ratio (each independent variable)
-     **lower_CI:** Lower confidence interval (each independent variable)
-     **upper_CI:** Upper confidence interval (each independent variable)
-     **variable:** Independent variable

Here is the script I am using in R:

# Calculate the standard error (seTE)

data$seTE <- (log(data$upper_CI) - log(data$lower_CI)) / (2 * 1.96)

# Meta-analysis

meta_analysis <- metagen(TE = log(data$AOR), 
                         seTE = data$seTE,
                         data = data,
                         studlab = data$study_id,
                         comb.fixed = TRUE, 
                         comb.random = TRUE)

# Meta-analysis results

summary(meta_analysis)

**I would like to know if this script is correct for achieving my goals of:**

    Calculating the pooled AOR and the 95% confidence interval.
    Calculating the I² and the p-value to assess heterogeneity.
   

Additionally, I am wondering about the necessity of using the **_log_** transformation in this context. Could someone explain why the logarithm of the AOR and confidence intervals is used in these calculations?

Any feedback or suggestions for improvement would be greatly appreciated!

Thank you!

**Comment by wviechtb** [comment]
Dear @sancho2023, this is not a support forum, but a place to report potential bugs or discuss/suggest feature enhancements to the package. As the issue template explains, general questions about the package should be posted to the [R-sig-meta-analysis](https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis) mailing list.
