### ISSUE TITLE
 Add `anova` for `permutest` or allow `btt` and `att` arguments to `permutest()`

### ISSUE THREAD

**Issue by FBartos** [wviechtb/metafor#88]
## Enhancement Suggestion

It would be very convenient if 
a) `anova.rma()` function worked with the `permutest.rma`
b) or `permutest()` function allowed passing `btt` and `att` arguments in the same way it is possible in the `anova.rma()` function.

Now, I'm required to create a completely new model using the `rma(..., btt = )` function call and then apply `permutest()` function.
(I hope it could be possible to reuse the `permutest.rma` results in the `anova()` function without redoing the permutations)?

Cheers,
Frantisek

**Comment by wviechtb** [comment]
With respect to b), this has already been added in the 'devel' version:

https://wviechtb.github.io/metafor/news/index.html#metafor-47-34-2024-09-30

With respect to a) -- not sure if this is possible. If you want to experiment with this, the permutation values are stored in elements `zval.perm` and `beta.perm` in the object returned by `permutest()`. Of course one can calculate linear combinations like `anova()` does based on `beta.perm` but I am not sure what the definition of the permutation-based p-value should then be.

**Comment by FBartos** [comment]
Oh cool, I missed that b) is already implemented, thanks!
Can't wait to see the new version on CRAN then.
