### ISSUE TITLE
naming the `random` list breaks the `dfbetas` function

### ISSUE THREAD

**Issue by FBartos** [wviechtb/metafor#89]
Hi Wolfgang,

This is quite an odd case which took me quite a while to identify: naming the `random` list breaks the `dfbetas` function:

```
dat <- escalc(measure="OR", ai=tpos, bi=tneg, ci=cpos, di=cneg, data=dat.bcg)
fit <- rma.mv(yi, vi, mods = ~year, random = list('Component1' = ~ 1 | trial/alloc), data = dat)

dfbetas(fit)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
```

(I name the list just to keep track of my generated code, so, this issue can be easily side-stepped by not specifying the names.)

Cheers,
Frantisek

**Comment by wviechtb** [comment]
That's a weird one -- thanks for pointing this out! Is this specific to `dfbetas()` or do some other methods also crap out when `random` list elements are named?
