### ISSUE TITLE
Documentation to clarify that ‘transf.lnorrtorr’ transforms to the risk ratio not the log risk ratio

### ISSUE THREAD

**Issue by befriendabacterium** [wviechtb/metafor#90]
## Classification:

Enhancement Suggestion

## Summary

This is a very quick one, but it wasn’t immediately clear to me that the ‘transf.lnorrtorr’ function transforms to the risk ratio rather than the log risk ratio. The confusion arose because escalc’s ‘RR’ option generates the log risk ratio, leading me to think this did the same. It might be a relatively rare source of confusion but maybe just an additional sentence in this and any other functions transforming to risk ratio, to clarify that it generates the risk ratio not the log risk ratio could help reduce potential confusion further? Should be dead quick to add! Thanks!

**Comment by wviechtb** [comment]
In b2d709f, I have added a note about this to the docs.
