### ISSUE TITLE
escalc: `vtype = "AV2"` and `measure = "R2"` error 

### ISSUE THREAD

**Issue by FBartos** [wviechtb/metafor#93]
From my understanding of the documentation, `"AV"` and `"AV2"` should be possible arguments for the `vtype` argument in the `escalc()` function regardless of whether the measure is `"R2"` or `"ZR2"`. However, `"R2"` & `"AV2"` throws and incorrect `vtype` error:

```
escalc(r2i = 0.5, mi = 2, ni = 100, measure = "R2", vtype = "AV")   # works
escalc(r2i = 0.5, mi = 2, ni = 100, measure = "R2", vtype = "AV2")  # error

escalc(r2i = 0.5, mi = 2, ni = 100, measure = "ZR2", vtype = "AV")  # works
escalc(r2i = 0.5, mi = 2, ni = 100, measure = "ZR2", vtype = "AV2") # works
```

**Comment by wviechtb** [comment]
Ah, good catch. Will fix this asap.

**Comment by wviechtb** [comment]
I just made an update (3e84c4c) that addresses the issue above (and that added measures `R2F` and `ZR2F`).

**Comment by FBartos** [comment]
Thanks!
