### ISSUE TITLE
Using Confidence Intervals Directly in rma Function Without Recalculating Standard Error

### ISSUE THREAD

**Issue by DavidReissig** [wviechtb/metafor#94]
Dear Wolfgang,

I am working on a meta-analysis project using the metafor package and have encountered a challenge regarding the use of confidence intervals reported in primary studies.

In my analysis, the confidence intervals calculated by the rma function often do not align with the published values from the primary studies. This discrepancy seems to arise because the confidence intervals are recalculated based on the standard error (sei) or sampling variance (vi), rather than using the reported confidence intervals directly.

I attempted to modify the rma function to utilize the extracted confidence intervals without recalculating them from the standard error. However, I faced issues due to the requirement of specifying sei or vi, which prevents a direct use of the confidence intervals.

I would like to ask if there is a way to directly use the confidence intervals in the rma function?

Thank you in advance for your assistance and for developing such an excellent tool for meta-analysis.

Best regards,
David

**Comment by wviechtb** [comment]
To do a meta-analysis, one needs the SEs. However, the kind of discrepancy is really only relevant when drawing a forest plot. Here, you can specify the CI bounds yourself. An example along those lines is shown here: https://www.metafor-project.org/doku.php/tips:forest_plot_with_exact_cis
